// Le trombinoscope des adhérents : une ligne par membre.
// Saison 2026-2027 · 132 adhérents.
// Pour ajouter un headshot : photo:'membres/prenom.jpg' (les initiales s'affichent sinon).
// Pour ajouter une citation : citation:'…' (le verso reste neutre si vide).
const MEMBRES=[
  {nom:'Candice', citation:'Mieux vaut avoir des courbatures que des regrets.', photo:''},
  {nom:'Thomas n°1', citation:'Viva la vida.', photo:''},
  {nom:'Manon n°1', citation:'Plus vite on commence, plus vite on termine.', photo:''},
  {nom:'Clarisse n°1', citation:'', photo:''},
  {nom:'Thomas n°2', citation:'', photo:''},
  {nom:'Ethan', citation:'Passionné de course à pied et de rencontres avec d\'autres coureurs.', photo:''},
  {nom:'Matteo n°1', citation:'La vie c\'est comme une boîte de chocolat : ça coûte cher, on fait semblant d\'aimer, mais on se rend vite compte que c\'est écœurant !', photo:''},
  {nom:'Quentin n°1', citation:'Visez la lune en gardant les pieds sur terre.', photo:''},
  {nom:'Romane n°1', citation:'Vive le Sud-Ouest !', photo:''},
  {nom:'Elisa', citation:'', photo:''},
  {nom:'Lorenzo', citation:'', photo:''},
  {nom:'Mathéo', citation:'', photo:''},
  {nom:'Alvin', citation:'Je suis très fier de représenter le club Le Ciel Bleu.', photo:''},
  {nom:'Agathe n°1', citation:'', photo:''},
  {nom:'Julien n°1', citation:'Yuli : le dealer de good mood.', photo:''},
  {nom:'Mélanie', citation:'', photo:''},
  {nom:'Sarah', citation:'', photo:''},
  {nom:'Victor n°1', citation:'La chance paie parfois, le travail toujours.', photo:''},
  {nom:'Thibault', citation:'', photo:''},
  {nom:'Lucile', citation:'Le ciel est bleu en deux mots ? Ciel bleu.', photo:''},
  {nom:'Clemence', citation:'', photo:''},
  {nom:'Julien n°2', citation:'Bonjour, je suis coach.', photo:''},
  {nom:'Yoann', citation:'On m\'a dit « méfiez-vous » en arrivant l\'an dernier : ils avaient raison, je suis devenu addict au Ciel Bleu.', photo:''},
  {nom:'Thomas « El coche »', citation:'Les relations humaines, vous savez…', photo:''},
  {nom:'Hugo n°1', citation:'Après chaque montée, il y a une descente.', photo:''},
  {nom:'Fanny n°1', citation:'', photo:''},
  {nom:'Théo n°1', citation:'Entraînement difficile, course facile.', photo:''},
  {nom:'Enzo', citation:'', photo:''},
  {nom:'Maxence', citation:'', photo:''},
  {nom:'Milena', citation:'', photo:''},
  {nom:'Baptiste', citation:'Better done than perfect.', photo:''},
  {nom:'Ludivine', citation:'', photo:''},
  {nom:'Clémence', citation:'Petite phrase à se répéter sans modération pendant qu\'on crache nos poumons : « on n\'est pas des merguez ».', photo:''},
  {nom:'Anaïs', citation:'', photo:''},
  {nom:'Marie', citation:'', photo:''},
  {nom:'Floriane', citation:'', photo:''},
  {nom:'Flavie', citation:'', photo:''},
  {nom:'Mathilde n°1', citation:'Je veux aller loin, mais surtout ne jamais arrêter d\'avancer.', photo:''},
  {nom:'Enora', citation:'', photo:''},
  {nom:'Quentin n°2', citation:'Qu\'est-ce que signifie « apprivoiser » ? C\'est une chose trop oubliée. Ça signifie « créer des liens ».', photo:''},
  {nom:'Mathieu n°1', citation:'La confiance n\'exclut pas le contrôle.', photo:''},
  {nom:'Alban', citation:'Tout le monde est sympa sauf moi.', photo:''},
  {nom:'Justine', citation:'', photo:''},
  {nom:'Julia', citation:'Je suis fan de Clem qui court.', photo:''},
  {nom:'Matheo', citation:'', photo:''},
  {nom:'Julien n°3', citation:'J\'ai couru le marathon de New York.', photo:''},
  {nom:'Leonardo', citation:'42 km ? En moto oui !', photo:''},
  {nom:'Agathe n°2', citation:'', photo:''},
  {nom:'Yohan', citation:'Heureux d\'être content.', photo:''},
  {nom:'Adèle', citation:'Oublies que tu as aucune chance, sur un malentendu ça peut marcher.', photo:''},
  {nom:'Kalome', citation:'', photo:''},
  {nom:'Manon n°2', citation:'Je ne perds jamais. Soit je gagne, soit j\'apprends.', photo:''},
  {nom:'Solène', citation:'', photo:''},
  {nom:'Hugo n°2', citation:'Grand rêve nécessite grand sacrifice.', photo:''},
  {nom:'Noémie', citation:'', photo:''},
  {nom:'Thomas n°4', citation:'Thomvol Golgoth.', photo:''},
  {nom:'Imogen', citation:'Audacieuse.', photo:''},
  {nom:'Mare', citation:'', photo:''},
  {nom:'Lou', citation:'', photo:''},
  {nom:'Fanny n°2', citation:'Je sais pas où je vais, mais j\'y vais en courant.', photo:''},
  {nom:'Eva', citation:'La vie c\'est ce qui arrive quand tu ne l\'avais pas prévu.', photo:''},
  {nom:'Aline', citation:'Jamais deux sans trois.', photo:''},
  {nom:'Maéva', citation:'', photo:''},
  {nom:'Sabrina', citation:'I\'m not superstitious, but I\'m a little stitious.', photo:''},
  {nom:'Apollonia', citation:'', photo:''},
  {nom:'Romane n°2', citation:'La discipline pour progresser, motivation pour avancer, plaisir pour continuer.', photo:''},
  {nom:'Anna', citation:'', photo:''},
  {nom:'Clara', citation:'On n\'a pas peur du bonheur ici.', photo:''},
  {nom:'Louise', citation:'Fume la vie avant que la vue ne te fume.', photo:''},
  {nom:'Maha', citation:'No pain no gain.', photo:''},
  {nom:'Yaël', citation:'Dans 500 m, y\'a la buvette.', photo:''},
  {nom:'Bastien', citation:'Courir avec le smile.', photo:''},
  {nom:'Matteo n°2', citation:'Tout ce que je sais, c\'est que je ne sais rien.', photo:''},
  {nom:'Gauthier', citation:'', photo:''},
  {nom:'Jason', citation:'Avec un peu d\'entraînement, les JO ça se fait bien.', photo:''},
  {nom:'Théo n°2', citation:'C\'est de la zinzinnerie !', photo:''},
  {nom:'Fabien', citation:'', photo:''},
  {nom:'Arthur', citation:'', photo:''},
  {nom:'Raphaël', citation:'', photo:''},
  {nom:'Guillaume n°1', citation:'Boire, c\'est la victoire.', photo:''},
  {nom:'Lino', citation:'Pour combien on accélère ?', photo:''},
  {nom:'Corentin', citation:'Toujours regarder à droite au passage piéton.', photo:''},
  {nom:'Théo n°3', citation:'Qui ne tente rien n\'a rien.', photo:''},
  {nom:'Axel', citation:'', photo:''},
  {nom:'Alain', citation:'', photo:''},
  {nom:'Benoît', citation:'Show must go on !', photo:''},
  {nom:'Gael', citation:'Plaisir rime aussi avec courir.', photo:''},
  {nom:'Hugo n°3', citation:'', photo:''},
  {nom:'Juliette', citation:'', photo:''},
  {nom:'Maxime', citation:'Witness the fitness.', photo:''},
  {nom:'Morgane n°1', citation:'', photo:''},
  {nom:'Adrien n°1', citation:'', photo:''},
  {nom:'Adrien n°2', citation:'', photo:''},
  {nom:'Alizée', citation:'', photo:''},
  {nom:'Alycia', citation:'Pas la plus rapide du CIELBLEU, mais sûrement la plus bleue.', photo:''},
  {nom:'Ameline', citation:'La vie me dépasse, alors je cours derrière.', photo:''},
  {nom:'Anais', citation:'', photo:''},
  {nom:'Anne Sophie', citation:'', photo:''},
  {nom:'Brieuc', citation:'I am speed.', photo:''},
  {nom:'Camille n°1', citation:'J\'aime courir, surtout quand c\'est bientôt fini.', photo:''},
  {nom:'Camille n°2', citation:'Sérieuse sans jamais se prendre au sérieux.', photo:''},
  {nom:'Camille n°3', citation:'', photo:''},
  {nom:'Charlotte', citation:'Jamais dans la demi-mesure.', photo:''},
  {nom:'Clarisse n°2', citation:'', photo:''},
  {nom:'Célia', citation:'', photo:''},
  {nom:'Dac-Huy', citation:'Manger, sport, voyage.', photo:''},
  {nom:'Emma', citation:'Le positif attire le positif.', photo:''},
  {nom:'Gaultier', citation:'Chante, Déesse, la colère d\'Achille, fils de Pélée.', photo:''},
  {nom:'Gaëlle', citation:'', photo:''},
  {nom:'Guillaume n°2', citation:'Pepito pianisto.', photo:''},
  {nom:'Hugo n°4', citation:'', photo:''},
  {nom:'Hugo n°5', citation:'', photo:''},
  {nom:'Jeanne n°1', citation:'Courir plus pour manger plus.', photo:''},
  {nom:'Jeanne n°2', citation:'Ne jamais me dire que je n\'en suis pas capable, sinon je devrais vous donner tort.', photo:''},
  {nom:'Jeanne n°3', citation:'', photo:''},
  {nom:'Jeremy', citation:'', photo:''},
  {nom:'Lola', citation:'', photo:''},
  {nom:'Maelle', citation:'', photo:''},
  {nom:'Margaux', citation:'', photo:''},
  {nom:'Margot', citation:'Mon secret : imaginer JUL sur la ligne d\'arrivée.', photo:''},
  {nom:'Mathieu n°2', citation:'Une belle journée pour être en vie.', photo:''},
  {nom:'Mathieu n°3', citation:'La seule mauvaise séance, c\'est celle que l\'on ne fait pas.', photo:''},
  {nom:'Mathilde n°2', citation:'', photo:''},
  {nom:'Maëlle', citation:'', photo:''},
  {nom:'Morgane n°2', citation:'', photo:''},
  {nom:'Romain', citation:'On court, mais pour aller où ? Ah, revenir au point de départ. Intéressant…', photo:''},
  {nom:'Samuel', citation:'', photo:''},
  {nom:'Thibaut', citation:'L\'effort fait les forts, les forts font l\'effort.', photo:''},
  {nom:'Thomas n°5', citation:'', photo:''},
  {nom:'Timothée', citation:'', photo:''},
  {nom:'Victor n°2', citation:'', photo:''},
  {nom:'Zoé', citation:'', photo:''}
];
