// Le trombinoscope des adhérents : une ligne par membre.
// Saison 2026-2027 · 56 adhérents.
// Pour ajouter un headshot : photo:'membres/prenom.jpg' (les initiales s'affichent sinon).
// Pour ajouter une citation : citation:'…' (le verso reste neutre si vide).
const MEMBRES=[
  {nom:'Candice', citation:'', photo:''},
  {nom:'Thomas', citation:'', photo:''},
  {nom:'Manon', citation:'', photo:''},
  {nom:'Clarisse', citation:'', photo:''},
  {nom:'Thomas', citation:'', photo:''},
  {nom:'Ethan', citation:'Passionné de course à pied et de rencontres avec d\'autres coureurs.', photo:''},
  {nom:'Matteo', citation:'La vie c\'est comme une boîte de chocolat : ça coûte cher, on fait semblant d\'aimer, mais on se rend vite compte que c\'est écœurant !', photo:''},
  {nom:'Quentin', citation:'', photo:''},
  {nom:'Romane', citation:'Vive le Sud-Ouest !', photo:''},
  {nom:'Elisa', citation:'', photo:''},
  {nom:'Lorenzo', citation:'', photo:''},
  {nom:'Mathéo', citation:'', photo:''},
  {nom:'Alvin', citation:'Je suis très fier de représenter le club Le Ciel Bleu.', photo:''},
  {nom:'Agathe n°1', citation:'', photo:''},
  {nom:'Julien', citation:'', photo:''},
  {nom:'Mélanie', citation:'', photo:''},
  {nom:'Sarah', citation:'', photo:''},
  {nom:'Victor', citation:'La chance paie parfois, le travail toujours.', photo:''},
  {nom:'Thibault', citation:'', photo:''},
  {nom:'Lucile', citation:'Le ciel est bleu en deux mots ? Ciel bleu.', photo:''},
  {nom:'Clemence', citation:'', photo:''},
  {nom:'Julien', citation:'', photo:''},
  {nom:'Yoann', citation:'On m\'a dit « méfiez-vous » en arrivant l\'an dernier : ils avaient raison, je suis devenu addict au Ciel Bleu.', photo:''},
  {nom:'Thomas', citation:'', photo:''},
  {nom:'Hugo', citation:'', photo:''},
  {nom:'Fanny', citation:'', photo:''},
  {nom:'Théo', citation:'Entraînement difficile, course facile.', photo:''},
  {nom:'Enzo', citation:'', photo:''},
  {nom:'Maxence', citation:'', photo:''},
  {nom:'Milena', citation:'', photo:''},
  {nom:'Baptiste', citation:'Better done than perfect.', photo:''},
  {nom:'Ludivine', citation:'', photo:''},
  {nom:'Clémence', citation:'Petite phrase à se répéter sans modération pendant qu\'on crache nos poumons : « on n\'est pas des merguez ».', photo:''},
  {nom:'Anaïs', citation:'', photo:''},
  {nom:'Marie', citation:'', photo:''},
  {nom:'Floriane', citation:'', photo:''},
  {nom:'Flavie', citation:'', photo:''},
  {nom:'Mathilde', citation:'', photo:''},
  {nom:'Enora', citation:'', photo:''},
  {nom:'Quentin', citation:'', photo:''},
  {nom:'Mathieu', citation:'La confiance n\'exclut pas le contrôle.', photo:''},
  {nom:'Alban', citation:'', photo:''},
  {nom:'Justine', citation:'', photo:''},
  {nom:'Julia', citation:'« Je savais pas que c\'était impossible, alors je l\'ai fait. » — Clem qui court', photo:''},
  {nom:'Matheo', citation:'', photo:''},
  {nom:'Julien', citation:'', photo:''},
  {nom:'Leonardo', citation:'42 km ? En moto oui !', photo:''},
  {nom:'Agathe n°2', citation:'', photo:''},
  {nom:'Yohan', citation:'Heureux d\'être content.', photo:''},
  {nom:'Adèle', citation:'Oublies que tu as aucune chance, sur un malentendu ça peut marcher.', photo:''},
  {nom:'Kalome', citation:'', photo:''},
  {nom:'Manon', citation:'', photo:''},
  {nom:'Solène', citation:'', photo:''},
  {nom:'Hugo', citation:'', photo:''},
  {nom:'Noémie', citation:'', photo:''},
  {nom:'Thomas', citation:'', photo:''}
];
