// Le trombinoscope des adhérents — une ligne par membre.
// Pour ajouter un headshot : photo:'membres/prenom.jpg' (les initiales s'affichent sinon).
const MEMBRES=[
  {nom:'Hugo', citation:'Le club a changé mon rapport à la course.', photo:''},
  {nom:'Thomas', citation:'Je viens pour les jambes, je reste pour les copains.', photo:''},
  {nom:'Julien', citation:'Mon meilleur chrono, c\'est ici que je l\'ai battu.', photo:''},
  {nom:'Candice', citation:'Courir seul, c\'est fini.', photo:''},
  {nom:'Manon', citation:'Les dimanches ont une autre saveur.', photo:''},
  {nom:'Alban', citation:'On souffre ensemble, on rit ensemble.', photo:''},
  {nom:'Floriane', citation:'Le café d\'après vaut tous les fractionnés.', photo:''},
  {nom:'Julia', citation:'J\'ai trouvé ma deuxième famille.', photo:''},
  {nom:'Mélanie', citation:'Chaque sortie est une petite aventure.', photo:''},
  {nom:'Damien', citation:'Le bitume parisien n\'a plus de secret pour moi.', photo:'membres/damien.jpg'},
  {nom:'Léa', citation:'Progresser sans pression, c\'est possible.', photo:''},
  {nom:'Antoine', citation:'Je ne pensais pas aimer la piste autant.', photo:''},
  {nom:'Camille', citation:'Des kilomètres, des fous rires, des souvenirs.', photo:''},
  {nom:'Maxime', citation:'Ici, personne n\'est laissé derrière.', photo:''},
  {nom:'Sarah', citation:'Le ciel est bleu, et mes runs aussi.', photo:'membres/sarah.jpg'},
  {nom:'Lucas', citation:'Venez essayer, vous comprendrez.', photo:''},
  {nom:'Emma', citation:'Le club a changé mon rapport à la course.', photo:''},
  {nom:'Paul', citation:'Je viens pour les jambes, je reste pour les copains.', photo:''},
  {nom:'Chloé', citation:'Mon meilleur chrono, c\'est ici que je l\'ai battu.', photo:''},
  {nom:'Nicolas', citation:'Courir seul, c\'est fini.', photo:''},
  {nom:'Inès', citation:'Les dimanches ont une autre saveur.', photo:''},
  {nom:'Romain', citation:'On souffre ensemble, on rit ensemble.', photo:''},
  {nom:'Marie', citation:'Le café d\'après vaut tous les fractionnés.', photo:''},
  {nom:'Théo', citation:'J\'ai trouvé ma deuxième famille.', photo:''},
  {nom:'Laura', citation:'Chaque sortie est une petite aventure.', photo:''},
  {nom:'Quentin', citation:'Le bitume parisien n\'a plus de secret pour moi.', photo:''},
  {nom:'Justine', citation:'Progresser sans pression, c\'est possible.', photo:''},
  {nom:'Adrien', citation:'Je ne pensais pas aimer la piste autant.', photo:''},
  {nom:'Pauline', citation:'Des kilomètres, des fous rires, des souvenirs.', photo:''},
  {nom:'Victor', citation:'Ici, personne n\'est laissé derrière.', photo:''},
  {nom:'Clara', citation:'Le ciel est bleu, et mes runs aussi.', photo:''},
  {nom:'Benjamin', citation:'Venez essayer, vous comprendrez.', photo:''},
  {nom:'Océane', citation:'Le club a changé mon rapport à la course.', photo:''},
  {nom:'Florian', citation:'Je viens pour les jambes, je reste pour les copains.', photo:''},
  {nom:'Anaïs', citation:'Mon meilleur chrono, c\'est ici que je l\'ai battu.', photo:''},
  {nom:'Mathieu', citation:'Courir seul, c\'est fini.', photo:''},
  {nom:'Élise', citation:'Les dimanches ont une autre saveur.', photo:''},
  {nom:'Guillaume', citation:'On souffre ensemble, on rit ensemble.', photo:''},
  {nom:'Margaux', citation:'Le café d\'après vaut tous les fractionnés.', photo:''},
  {nom:'Raphaël', citation:'J\'ai trouvé ma deuxième famille.', photo:''},
  {nom:'Solène', citation:'Chaque sortie est une petite aventure.', photo:''},
  {nom:'Baptiste', citation:'Le bitume parisien n\'a plus de secret pour moi.', photo:''},
  {nom:'Lucie', citation:'Progresser sans pression, c\'est possible.', photo:''},
  {nom:'Clément', citation:'Je ne pensais pas aimer la piste autant.', photo:''},
  {nom:'Jade', citation:'Des kilomètres, des fous rires, des souvenirs.', photo:''},
  {nom:'Arthur', citation:'Ici, personne n\'est laissé derrière.', photo:''},
  {nom:'Manon', citation:'Le ciel est bleu, et mes runs aussi.', photo:''},
  {nom:'Simon', citation:'Venez essayer, vous comprendrez.', photo:''},
  {nom:'Charlotte', citation:'Le club a changé mon rapport à la course.', photo:''},
  {nom:'Pierre', citation:'Je viens pour les jambes, je reste pour les copains.', photo:''},
  {nom:'Alice', citation:'Mon meilleur chrono, c\'est ici que je l\'ai battu.', photo:''},
  {nom:'Gabriel', citation:'Courir seul, c\'est fini.', photo:''},
  {nom:'Louise', citation:'Les dimanches ont une autre saveur.', photo:''},
  {nom:'Nathan', citation:'On souffre ensemble, on rit ensemble.', photo:''},
  {nom:'Zoé', citation:'Le café d\'après vaut tous les fractionnés.', photo:''},
  {nom:'Hugo', citation:'J\'ai trouvé ma deuxième famille.', photo:''},
  {nom:'Eva', citation:'Chaque sortie est une petite aventure.', photo:''},
  {nom:'Tom', citation:'Le bitume parisien n\'a plus de secret pour moi.', photo:''},
  {nom:'Léna', citation:'Progresser sans pression, c\'est possible.', photo:''},
  {nom:'Axel', citation:'Je ne pensais pas aimer la piste autant.', photo:''},
  {nom:'Mila', citation:'Des kilomètres, des fous rires, des souvenirs.', photo:''},
  {nom:'Enzo', citation:'Ici, personne n\'est laissé derrière.', photo:''},
  {nom:'Rose', citation:'Le ciel est bleu, et mes runs aussi.', photo:''},
  {nom:'Noah', citation:'Venez essayer, vous comprendrez.', photo:''},
  {nom:'Lina', citation:'Le club a changé mon rapport à la course.', photo:''},
  {nom:'Ethan', citation:'Je viens pour les jambes, je reste pour les copains.', photo:''},
  {nom:'Nina', citation:'Mon meilleur chrono, c\'est ici que je l\'ai battu.', photo:''},
  {nom:'Sacha', citation:'Courir seul, c\'est fini.', photo:''},
  {nom:'Anna', citation:'Les dimanches ont une autre saveur.', photo:''},
  {nom:'Tristan', citation:'On souffre ensemble, on rit ensemble.', photo:''},
  {nom:'Maya', citation:'Le café d\'après vaut tous les fractionnés.', photo:''},
  {nom:'Yanis', citation:'J\'ai trouvé ma deuxième famille.', photo:''},
  {nom:'Juliette', citation:'Chaque sortie est une petite aventure.', photo:''},
  {nom:'Kevin', citation:'Le bitume parisien n\'a plus de secret pour moi.', photo:''},
  {nom:'Sofia', citation:'Progresser sans pression, c\'est possible.', photo:''},
  {nom:'Dylan', citation:'Je ne pensais pas aimer la piste autant.', photo:''},
  {nom:'Léonie', citation:'Des kilomètres, des fous rires, des souvenirs.', photo:''},
  {nom:'Mehdi', citation:'Ici, personne n\'est laissé derrière.', photo:''},
  {nom:'Agathe', citation:'Le ciel est bleu, et mes runs aussi.', photo:''},
  {nom:'Bastien', citation:'Venez essayer, vous comprendrez.', photo:''},
  {nom:'Salomé', citation:'Le club a changé mon rapport à la course.', photo:''},
  {nom:'Corentin', citation:'Je viens pour les jambes, je reste pour les copains.', photo:''},
  {nom:'Maëlys', citation:'Mon meilleur chrono, c\'est ici que je l\'ai battu.', photo:''},
  {nom:'Loïc', citation:'Courir seul, c\'est fini.', photo:''},
  {nom:'Capucine', citation:'Les dimanches ont une autre saveur.', photo:''},
  {nom:'Jordan', citation:'On souffre ensemble, on rit ensemble.', photo:''},
  {nom:'Faustine', citation:'Le café d\'après vaut tous les fractionnés.', photo:''},
  {nom:'Rémi', citation:'J\'ai trouvé ma deuxième famille.', photo:''},
  {nom:'Apolline', citation:'Chaque sortie est une petite aventure.', photo:''},
  {nom:'Valentin', citation:'Le bitume parisien n\'a plus de secret pour moi.', photo:''},
  {nom:'Garance', citation:'Progresser sans pression, c\'est possible.', photo:''},
  {nom:'Hadrien', citation:'Je ne pensais pas aimer la piste autant.', photo:''},
  {nom:'Romane', citation:'Des kilomètres, des fous rires, des souvenirs.', photo:''},
  {nom:'Aurélien', citation:'Ici, personne n\'est laissé derrière.', photo:''},
  {nom:'Lou', citation:'Le ciel est bleu, et mes runs aussi.', photo:''},
  {nom:'Cyprien', citation:'Venez essayer, vous comprendrez.', photo:''},
  {nom:'Ambre', citation:'Le club a changé mon rapport à la course.', photo:''},
  {nom:'Côme', citation:'Je viens pour les jambes, je reste pour les copains.', photo:''},
  {nom:'Iris', citation:'Mon meilleur chrono, c\'est ici que je l\'ai battu.', photo:''},
  {nom:'Marius', citation:'Courir seul, c\'est fini.', photo:''},
];
